from __future__ import annotations

import ast
from hashlib import sha256
from pathlib import Path

from videoscope.providers.vision_worker_contract import (
    VISION_WORKER_CORE_DISTRIBUTIONS,
    VISION_WORKER_LOCK_SHA256,
    VISION_WORKER_RUNTIME_IDENTITY,
)


ROOT = Path(__file__).resolve().parents[2]


def _imported_roots(tree: ast.AST) -> set[str]:
    roots: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            roots.update(alias.name.split(".", 1)[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            roots.add(node.module.split(".", 1)[0])
    return roots


def test_vision_worker_has_a_dedicated_exact_project_and_lock() -> None:
    project = (ROOT / "workers/vision/pyproject.toml").read_text(encoding="utf-8")
    lock_path = ROOT / "workers/vision/requirements.lock"
    lock = lock_path.read_text(encoding="utf-8")

    assert 'requires-python = ">=3.12,<3.13"' in project
    assert lock.startswith(
        "# This file was autogenerated by uv via the following command:\n"
        "#    make lock-vision\n"
    )
    for distribution, version in VISION_WORKER_CORE_DISTRIBUTIONS.items():
        assert f'"{distribution}=={version}"' in project or (
            distribution == "uvicorn"
            and f'"uvicorn[standard]=={version}"' in project
        )
        assert f"{distribution}=={version}" in lock
    assert "rfdetr==1.7.1" in lock
    assert "transformers==5.14.1" in lock
    assert VISION_WORKER_LOCK_SHA256 == sha256(lock_path.read_bytes()).hexdigest()
    assert f"lock-sha256:{VISION_WORKER_LOCK_SHA256}" in VISION_WORKER_RUNTIME_IDENTITY
    assert "macos-major>=14" in VISION_WORKER_RUNTIME_IDENTITY
    assert "siglip-backend==mps" in VISION_WORKER_RUNTIME_IDENTITY
    assert "siglip-dtype==float32" in VISION_WORKER_RUNTIME_IDENTITY
    assert "rfdetr-backend==mps" in VISION_WORKER_RUNTIME_IDENTITY
    assert "rfdetr-dtype==float32" in VISION_WORKER_RUNTIME_IDENTITY
    assert (
        "mps-residency==exclusive-vision-backbone-v1"
        in VISION_WORKER_RUNTIME_IDENTITY
    )
    assert "detector-release==stage-bound-v1" in VISION_WORKER_RUNTIME_IDENTITY


def test_worker_and_client_contract_imports_do_not_load_ml_frameworks() -> None:
    forbidden = {"PIL", "rfdetr", "torch", "torchvision", "transformers"}
    for relative in (
        "backend/src/videoscope/providers/vision_worker_contract.py",
        "backend/src/videoscope/providers/vision_worker.py",
        "backend/src/videoscope/providers/vision_worker_client.py",
    ):
        tree = ast.parse((ROOT / relative).read_text(encoding="utf-8"))
        top_level = ast.Module(
            body=[
                node
                for node in tree.body
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            ],
            type_ignores=[],
        )
        assert _imported_roots(top_level).isdisjoint(forbidden)


def test_backend_project_does_not_own_isolated_worker_dependencies() -> None:
    backend_project = (ROOT / "backend/pyproject.toml").read_text(encoding="utf-8")

    assert "videoscope-vision-worker" not in backend_project
    for worker_dependency in ("rfdetr", "supervision", "torchvision", "transformers"):
        assert worker_dependency not in backend_project
